### ISSUE TITLE
error hash mismatch

### ISSUE THREAD

**Issue by W6Design** [arkin0x/construct-miner#1]
with last version, i get this error ( all browsers) 

Error: hash mismatch
    evaluateWork MinerController.tsx:136
    onWorkerResponse MinerController.tsx:79
[lockdown-install.js:1:103865](moz-extension://65a8d896-1791-4f61-9cfa-699c26ac09af/lockdown-install.js)
    functors moz-extension://65a8d896-1791-4f61-9cfa-699c26ac09af/lockdown-install.js:1

**Comment by arkin0x** [comment]
Yes, I have a solution for this but just need time to implement it. I would use a prior version for now, although it's kinda just not working no matter what at the moment 😆 so don't expect to keep anything you mine

**Comment by W6Design** [comment]
No problem, I will just wait the right version out . I was just updating and saw this error.  Just wanted to notice it.

**Comment by arkin0x** [comment]
This is fixed!
